name: Build Gradle project

inputs:
  java-version: {}

runs:
  using: composite
  steps:
    - name: Check out project sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Gradle properties
      id: get-gradle-properties
      uses: .github/actions/read-gradle-properties/action.yml
      with:
        keys: java_version

    - name: Resolve environment variables
      run: |
        echo "${{ needs.get-gradle-properties.outputs.entries }}" >> $GITHUB_ENV
        if [ -n "${{ inputs.java-version }}" ]; then \
          echo "JAVA_VERSION='${{ inputs.java-version }}'" >> $GITHUB_ENV; \
        fi
      shell: bash

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: temurin

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: https://gradle.com/terms-of-service
        build-scan-terms-of-use-agree: yes

    - name: Generate wrapper
      run: gradle wrapper
      shell: bash

    - name: Run build
      run: ./gradlew build
      shell: bash
