name: Publish on GitHub & Modrinth

on:
  workflow_dispatch:
    inputs:
      java-version: {}
      mod-version: {}
      mc-version: {}
      mc-target-version: {}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Java version
        id: get-java-version
        if: ${{ inputs.java-version }} == ''
        uses: .github/actions/read-gradle-properties/action.yml
        with:
          key: java_version

      - name: Get mod version
        id: get-mod-version
        if: ${{ inputs.mod-version }} == ''
        uses: .github/actions/read-gradle-properties/action.yml
        with:
          key: mod_version

      - name: Get Minecraft version
        id: get-mc-version
        if: ${{ inputs.mc-version }} == ''
        uses: .github/actions/read-gradle-properties/action.yml
        with:
          key: minecraft_version

      - name: Get Minecraft target version
        id: get-mc-target-version
        if: ${{ inputs.mc-target-version }} == ''
        uses: .github/actions/read-gradle-properties/action.yml
        with:
          key: minecraft_target_version

      - name: Resolve environment variables
        run: |
          echo "JAVA_VERSION=${${{ inputs.java-version }}:-${{ needs.get-java-version.outputs.value }}}" >> $GITHUB_ENV
          echo "MOD_VERSION=${${{ inputs.mod-version }}:-${{ needs.get-mod-version.outputs.value }}}" >> $GITHUB_ENV
          echo "MC_VERSION=${${{ inputs.mc-version }}:-${{ needs.get-mc-version.outputs.value }}}" >> $GITHUB_ENV
          echo "MC_TARGET_VERSION=${${{ inputs.mc-target-version }}:-${{ needs.get-mc-target-version.outputs.value }}}" >> $GITHUB_ENV

      - name: Build Gradle project
        uses: ./.github/workflows/build.yml

      - name: Publish project
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: v${{ env.MOD_VERSION }} for Minecraft ${{ env.MC_VERSION }}
          version: ${{ env.MOD_VERSION }}+${{ env.MC_VERSION }}
          version-type: release

          java: ${{ env.JAVA_VERSION }}
          game-versions: ${{ env.MC_TARGET_VERSION }}
          loaders: fabric

          github-generate-changelog: true
          github-tag: v${{ env.MOD_VERSION }}+${{ env.MC_VERSION }}
          github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-featured: true
          modrinth-token: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
